language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
  - 6
env:
  - BUILD_LEADER_ID=1
after_success:
  - npm install -g semantic-release
  - npm install --no-save semantic-release-tamia
  - semantic-release pre && npm publish && semantic-release post
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
