language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 6
  - 8
after_success:
  - npm install -g semantic-release semantic-release-tamia
  - semantic-release pre && npm publish && semantic-release post
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
